name: "🐛 Report bugs"
description: "The template for reporting bugs for this project."
title: "[🐛Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much information as you can to help us reproduce and fix the issue.

  - type: dropdown
    id: bug_severity
    attributes:
      label: "🎲Solution"
      description: "Select the where is the bug occur."
      options:
        - label: "API"
          value: "api"
        - label: "Web"
          value: "web"
        - label: "Docs"
          value: "docs"
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: "🐛 Bug Description"
      description: "Describe the bug in detail."
      placeholder: "A clear and concise description of what the bug is."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "🛠️ Steps to Reproduce"
      description: "List the steps to reproduce the bug."
      placeholder: "1. Go to '...'\n2. Click on '...'\n3. Scroll down to '...'\n4. See error"
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "✅ Expected Behavior"
      description: "Describe what you expected to happen."
      placeholder: "A clear and concise description of what you expected to happen."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        Please ensure all relevant information is provided to help us address the issue promptly. Thank you!
